#!/bin/sh

set -e

[ -z "$mount_as" ] && mount_as=0
[ -z "$run_as" ] && run_as=0

mkdir -p /overlay/upper /overlay/work /docked

[ -f /sys/module/overlay/parameters/metacopy ] && metacopy=1
mount -t \
    overlay overlay \
    -o lowerdir=/host,upperdir=/overlay/upper,workdir=/overlay/work${metacopy:+,metacopy=on} \
    /docked

chown -R "$mount_as:$(id -g $mount_as)" /docked
cd /docked

su "$run_as" -s "$(dirname "$0")/dockit-sh"
