#!/bin/sh

set -e

[ -z "$mount_as" ] && mount_as=0
[ -z "$run_as" ] && run_as=0

mkdir -p /overlay/upper /overlay/work /docked

[ -f /sys/module/overlay/parameters/metacopy ] && metacopy=1
mount -t \
    overlay overlay \
    -o lowerdir=/host,upperdir=/overlay/upper,workdir=/overlay/work${metacopy:+,metacopy=on} \
    /docked

cd /docked

if [ -z "$ignore_skip" ]
then
    for ignorefile in .gitignore .dockerignore
    do
        if [ -f "$ignorefile" ]
        then
            while read line
            do
                find -type d -name "${line%/}" -prune -exec /bin/sh -c \
                    "mv {} {}.trashed ; rm -rf /overlay/upper/{}.trashed" \;
                find -type f -name "$line" -exec rm {} \;
            done < "$ignorefile"
        fi
    done
fi

chown -R "$mount_as:$(id -g $mount_as)" /docked

su "$run_as" -s "$(dirname "$0")/dockit-sh"
