#!/bin/sh

set -e

while getopts ":m:r:" opt
do
    case $opt in
        m)
            mount_as=$OPTARG
            ;;
        r)
            run_as=$OPTARG
            ;;
        \?)
            echo "Unrecognized option: -$OPTARG"
            exit 1
            ;;
        :)
            echo "-$OPTARG requires an argument" 1>&2
            exit 1
            ;;
    esac
done
shift $(($OPTIND-1))

if [ -z "$mount_as" ]
then
    echo "-m is required" 1>&2
    exit 1
fi

if [ -z "$run_as" ]
then
    echo "-r is required" 1>&2
    exit 1
fi

mount -t tmpfs tmpfs /tmp
mkdir -p /tmp/upper /tmp/overlay /docked

[ -f /sys/module/overlay/parameters/metacopy ] && metacopy=1
mount -t \
    overlay overlay \
    -o lowerdir=/host,upperdir=/tmp/upper,workdir=/tmp/overlay${metacopy:+,metacopy=on} \
    /docked

chown -R $mount_as:$(id -g $mount_as) /docked
cd /docked

if [ -f /bin/bash ]
then
    su $run_as -c /bin/bash
else
    su $run_as -c /bin/sh
fi
