#!/bin/sh

if [ $# -eq 0 ]
then
    echo "Usage: undock <file1> [<file2>]..."
    exit
fi

hostuser=$(ls -ld /host | awk '{print $3}')
hostgroup=$(ls -ld /host | awk '{print $4}')
dockuser=$(ls -ld /docked | awk '{print $3}')
dockgroup=$(ls -ld /docked | awk '{print $4}')
tmp=$(mktemp -d)

for file in "$@"
do
    mv $file /tmp/$file
    mv /tmp/$file /host/$file
    chown -R $hostuser:$hostgroup /host/$file
    chown -R $dockuser:$dockgroup $file
done

rm -rf $tmp
