#!/bin/sh

if [ $# -eq 0 ]
then
    echo "Usage: undock <file1> [<file2>]..."
    exit
fi

hostuser=$(ls -ld /host | awk '{print $3}')
hostgroup=$(ls -ld /host | awk '{print $4}')
dockuser=$(ls -ld /docked | awk '{print $3}')
dockgroup=$(ls -ld /docked | awk '{print $4}')
tmp=$(mktemp -d)

for file in "$@"
do

    fullpath=$(readlink -f "$file")
    if [ ! -f "$fullpath" ]
    then
        echo "$file does not exist or is a directory"
    fi

    case $fullpath in
        /docked/*) ;;
        *)
            echo "$file is not in /docked"
            exit 1
        ;;
    esac

    relpath=$(echo "$fullpath" | sed 's/\/docked\/\(.\+\)/\1/')
    reldir=$(echo "$relpath" | sed "s/^\\(.*\\)$(basename "$fullpath")\$/\\1/")

    mkdir -p "/host/$reldir"
    cp "$fullpath" "/host/$relpath"

    chown -R "$hostuser:$hostgroup" "/host/$reldir"
    chown -R "$dockuser:$dockgroup" "/docked/$reldir"

done

rm -rf "$tmp"
