#!/bin/sh

if [ $# -eq 0 ]
then
    echo "Usage: undock <file1> [<file2>]..."
    exit
fi

hostuser=$(ls -ld /host | awk '{print $3}')
hostgroup=$(ls -ld /host | awk '{print $4}')
dockuser=$(ls -ld /docked | awk '{print $3}')
dockgroup=$(ls -ld /docked | awk '{print $4}')
tmp=$(mktemp -d)

for file in "$@"
do

    fullpath=$(readlink -f "$file")
    dirname=$(dirname "$fullpath")
    basename=$(basename "$fullpath")

    if [ ! "$dirname" = "/docked" ]
    then
        echo "$1 is not inside of /docked"
        exit 1
    fi

    mv "$fullpath" "/tmp/$basename"
    mv "/tmp/$basename" "/host/$basename"

    chown -R "$hostuser:$hostgroup" "/host/$basename"
    chown -R "$dockuser:$dockgroup" "$fullpath"

done

rm -rf "$tmp"
